
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.tempuri;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-12T09:49:52.128+03:00
 * Generated source version: 3.2.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "UDSDocumentSrvcLib",
                      portName = "BasicHttpBinding_IUDSDocumentSrvcLib",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "http://w-jhq-udst/UDSDocument/UDSDocumentService.svc?wsdl",
                      endpointInterface = "org.tempuri.IUDSDocumentSrvcLib")
                      
public class BasicHttpBinding_IUDSDocumentSrvcLibImpl implements IUDSDocumentSrvcLib {

    private static final Logger LOG = Logger.getLogger(BasicHttpBinding_IUDSDocumentSrvcLibImpl.class.getName());

    /* (non-Javadoc)
     * @see org.tempuri.IUDSDocumentSrvcLib#getConnectionAgreement(java.lang.Integer reqID)*
     */
    public org.datacontract.schemas._2004._07.udsdocument.ConnectionAgreement getConnectionAgreement(java.lang.Integer reqID) throws IUDSDocumentSrvcLibGetConnectionAgreementServiceResponseFaultFaultMessage   { 
        LOG.info("Executing operation getConnectionAgreement");
        System.out.println(reqID);
        try {
            org.datacontract.schemas._2004._07.udsdocument.ConnectionAgreement _return = new org.datacontract.schemas._2004._07.udsdocument.ConnectionAgreement();
            javax.xml.bind.JAXBElement<org.datacontract.schemas._2004._07.CustomerData> _returnCustData = null;
            _return.setCustData(_returnCustData);
            javax.xml.bind.JAXBElement<org.datacontract.schemas._2004._07.ArrayOfReqDetailExist> _returnExistReqTypeList = null;
            _return.setExistReqTypeList(_returnExistReqTypeList);
            javax.xml.bind.JAXBElement<org.datacontract.schemas._2004._07.LocationData> _returnLocData = null;
            _return.setLocData(_returnLocData);
            javax.xml.bind.JAXBElement<org.datacontract.schemas._2004._07.ArrayOfReqDetailNew> _returnNewReqTypeList = null;
            _return.setNewReqTypeList(_returnNewReqTypeList);
            javax.xml.bind.JAXBElement<org.datacontract.schemas._2004._07.ArrayOfRequestType> _returnReqTypeList = null;
            _return.setReqTypeList(_returnReqTypeList);
            javax.xml.bind.JAXBElement<org.datacontract.schemas._2004._07.RequestData> _returnReqtData = null;
            _return.setReqtData(_returnReqtData);
            javax.xml.bind.JAXBElement<org.datacontract.schemas._2004._07.udsdocument.ServiceResponse> _returnResponse = null;
            _return.setResponse(_returnResponse);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IUDSDocumentSrvcLibGetConnectionAgreementServiceResponseFaultFaultMessage("IUDSDocumentSrvcLib_getConnectionAgreement_ServiceResponseFault_FaultMessage...");
    }

}
