
package org.tempuri;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-12T09:49:52.112+03:00
 * Generated source version: 3.2.0
 */

@WebFault(name = "ServiceResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/UDSDocument")
public class IUDSDocumentSrvcLibGetConnectionAgreementServiceResponseFaultFaultMessage extends Exception {
    
    private org.datacontract.schemas._2004._07.udsdocument.ServiceResponse serviceResponse;

    public IUDSDocumentSrvcLibGetConnectionAgreementServiceResponseFaultFaultMessage() {
        super();
    }
    
    public IUDSDocumentSrvcLibGetConnectionAgreementServiceResponseFaultFaultMessage(String message) {
        super(message);
    }
    
    public IUDSDocumentSrvcLibGetConnectionAgreementServiceResponseFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IUDSDocumentSrvcLibGetConnectionAgreementServiceResponseFaultFaultMessage(String message, org.datacontract.schemas._2004._07.udsdocument.ServiceResponse serviceResponse) {
        super(message);
        this.serviceResponse = serviceResponse;
    }

    public IUDSDocumentSrvcLibGetConnectionAgreementServiceResponseFaultFaultMessage(String message, org.datacontract.schemas._2004._07.udsdocument.ServiceResponse serviceResponse, Throwable cause) {
        super(message, cause);
        this.serviceResponse = serviceResponse;
    }

    public org.datacontract.schemas._2004._07.udsdocument.ServiceResponse getFaultInfo() {
        return this.serviceResponse;
    }
}
