package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-06T15:58:03.118+03:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "UDSDocumentSrvcLib", 
                  wsdlLocation = "http://w-jhq-udst/UDSDocument/UDSDocumentService.svc?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class UDSDocumentSrvcLib extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "UDSDocumentSrvcLib");
    public final static QName BasicHttpBindingIUDSDocumentSrvcLib = new QName("http://tempuri.org/", "BasicHttpBinding_IUDSDocumentSrvcLib");
    static {
        URL url = null;
        try {
            url = new URL("http://w-jhq-udst/UDSDocument/UDSDocumentService.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UDSDocumentSrvcLib.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://w-jhq-udst/UDSDocument/UDSDocumentService.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UDSDocumentSrvcLib(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UDSDocumentSrvcLib(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UDSDocumentSrvcLib() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UDSDocumentSrvcLib(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UDSDocumentSrvcLib(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UDSDocumentSrvcLib(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IUDSDocumentSrvcLib
     */
    @WebEndpoint(name = "BasicHttpBinding_IUDSDocumentSrvcLib")
    public IUDSDocumentSrvcLib getBasicHttpBindingIUDSDocumentSrvcLib() {
        return super.getPort(BasicHttpBindingIUDSDocumentSrvcLib, IUDSDocumentSrvcLib.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IUDSDocumentSrvcLib
     */
    @WebEndpoint(name = "BasicHttpBinding_IUDSDocumentSrvcLib")
    public IUDSDocumentSrvcLib getBasicHttpBindingIUDSDocumentSrvcLib(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIUDSDocumentSrvcLib, IUDSDocumentSrvcLib.class, features);
    }

}
